// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Abort(arg1:Record<string, any>):Promise<Record<string, any>>;

export function Chat(arg1:main.chatPayload):Promise<Record<string, any>>;

export function ClipboardImage():Promise<Record<string, any>>;

export function DeleteApiKey(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetApiKeyStatus(arg1:Record<string, any>):Promise<Record<string, any>>;

export function ModelStats():Promise<Record<string, any>>;

export function Models():Promise<Record<string, any>>;

export function SaveApiKey(arg1:Record<string, any>):Promise<Record<string, any>>;

export function WebSearch(arg1:Record<string, any>):Promise<Record<string, any>>;
