// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort(arg1) {
  return window['go']['main']['App']['Abort'](arg1);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ClipboardImage() {
  return window['go']['main']['App']['ClipboardImage']();
}

export function DeleteApiKey(arg1) {
  return window['go']['main']['App']['DeleteApiKey'](arg1);
}

export function GetApiKeyStatus(arg1) {
  return window['go']['main']['App']['GetApiKeyStatus'](arg1);
}

export function ModelStats() {
  return window['go']['main']['App']['ModelStats']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function SaveApiKey(arg1) {
  return window['go']['main']['App']['SaveApiKey'](arg1);
}

export function WebSearch(arg1) {
  return window['go']['main']['App']['WebSearch'](arg1);
}
